### ISSUE TITLE
Documentation of transform_form_pq misleading

### ISSUE THREAD

**Issue by HWiese1980** [rock-learning/pytransform#1]
Hi,

in my opinion the documentation of `transform_from_pq` is a bit misleading. From the paramater list `(x, y, z, w, vx, vy, vz)` it's not particularly clear which x, y, z belongs to the quaternion and which is the cartesian point. Since `w` doesn't have a prefix it might very well belong to the first three parameters and the second set `vx, vy, vz` might equally well be understood as `vector x, vector y, vector z`. 

This should be pointed out clearer in the documentation in my opinion. I haven't looked yet if this also affects other functions.

**Comment by AlexanderFabisch** [comment]
In this case vx refers to the *vector* component of the quaternion. This should be clearer in the documentation.

**Comment by AlexanderFabisch** [comment]
Would this be better?

```
Position (x, y, z) and orientation quaternion (w, vx, vy, vz): (x, y, z, w, vx, vy, vz)
```

**Comment by HWiese1980** [comment]
You could also name the parameters `qw, qx, qy, qz`. That way it is directly clearly visible from the names of the parameters what their purpose is, without the need to look at the function documentation. That's how I usually mark quaternion components. 

But I guess your suggestion would be fine too.
