### ISSUE TITLE
Active vs. passive, what should we use as a standard?

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-learning/pytransform#6]
[Wikipedia](https://en.wikipedia.org/wiki/Active_and_passive_transformation)

Should rotations or transformations transform points to new locations in the coordinate frame or should they transform coordinate systems?

@HWiese1980 maybe you have an idea.

**Comment by HWiese1980** [comment]
In my humble opinion, it clearly... depends. In the case that you only need to transform a single pose (and nothing else that might rely on it) in a frame of reference (FOR) I think you can just transform the pose itself. Do you need everything underneath that FOR in a hierarchy of FORs to be transformed, it might be better to transform the whole FOR.

**Comment by HWiese1980** [comment]
An active transformation might be easier to grasp, though. Especially when multiple subsequent transformations are combined.

**Comment by AlexanderFabisch** [comment]
I think active / alibi is what we use currently: https://github.com/rock-learning/pytransform/blob/master/pytransform/rotations.py#L376

However, I am at the moment mostly working with passive transformations in the context of RoCK and EnviRe, which makes me think that these are used more often?
