### ISSUE TITLE
Make it animatable

### ISSUE THREAD

**Issue by HWiese1980** [rock-learning/pytransform#9]
Not sure if it's already implemented in some not obvious way, but... I would like to see the library enhanced in a way that plotting the frames/links can be more easily animated. Currently, if I'm not mistaken, it's just `plot`ting, is that right? 
In an animation setup like for example `FuncAnimation` you'd use `set_data` to refresh the plot without having to plot everything again (which is very time consuming). Or does `pytransform` already offer that too? Might be that I've missed something...

**Comment by AlexanderFabisch** [comment]
I'll take a lookk at [PyQtGraph](http://pyqtgraph.org/) for InFuse at the moment. Maybe that would be something for you.
